version: '3.8'

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 80:3000
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://database:27017/cars_production
    depends_on:
      - database
  tests:
    container_name: tests
    build:
      context: ./server
      dockerfile: Dockerfile_test
    ports:
      - 3000:3000
    environment:
      NODE_ENV: test
      MONGO_URI: mongodb://database/cars_test
    depends_on:
      - database
  database:
    container_name: database
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - cars:/data/db

volumes:
  cars: null